[package]
name = "tinyccrl-engine"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "tinyccrl-engine"
path = "src/main.rs"

[dependencies]
chess = "3.2"
wasm-bindgen = { version = "0.2", optional = true }
console_error_panic_hook = { version = "0.1", optional = true }

[features]
wasm = ["wasm-bindgen", "console_error_panic_hook"]
